name: Actions WorkFlow


on: 
   push:
     branches:
       - master
       - 'feature/*' #matches feature/featA, feature/featB doen't match feature/feat/a
       - 'feature/**' #matches feature/feat/a or feature/featB
       - '!feature/featC'
     tags:
        - 'v1.*'
     paths:
        - '**.js' # this workflow will run if we push anything in js files , if we push and change non.js files this workflow will not run
        # ignore .js file by add '!filename.js'
   #  path-ignore:
      #    - '!docs/**'
 #  branches-ignore:
      #    - null
jobs:
      run-github-actions:
        runs-on: ubuntu-latest

        steps: 
           - name: Secret key varibale to use
             run: |
                 pwd
                 ls -a
                 echo $GITHUB_SHA
                 echo $GITHUB_REPOSITORY
                 echo $GGITHUB_WORKSPACE
                 echo "{{github}}"
                 ls -a 
                 pwd
           - name: Checkout
             uses: actions/checkout@v1
           - name: List Files
             run: |
                pwd
                ls -a
           - name: Simple JS Action
             id: greet
             uses: Kijacode/hello-world-javascript-action@main
             with:
                  who-to-greet: Kijacode
           - name: Log Greeting Time
             run: echo "${{steps.greet.outputs.time}}"
                 
