name: Actions WorkFlow


on: [push,pull_request  ]

jobs:
      run-github-actions:
        runs-on: ubuntu-latest

        steps: 
           - name: Secret key varibale to use
             run: |
                 pwd
                 ls -a
                 echo $GITHUB_SHA
                 echo $GITHUB_REPOSITORY
                 echo $GGITHUB_WORKSPACE
                 echo "{{github}}"
                 ls -a 
                 pwd
           - name: Checkout
             uses: actions/checkout@v1
           - name: List Files
             run: |
                pwd
                ls -a
           - name: Simple JS Action
             id: greet
             uses: Kijacode/hello-world-javascript-action@main
             with:
                  who-to-greet: Kijacode
           - name: Log Greeting Time
             run: echo "${{steps.greet.outputs.time}}"
                 
